/*
 * HTMLGenerator, $RCSfile: DatabaseInterface.java,v $
 *
 * $Revision: 1.4 $
 * $Date: 2003/06/29 13:34:19 $
 *
 * $Author: humble $
 * Original Author: Jan Humble
 */

package ipdlx.tools;

import ipdlx.*;
import java.util.Enumeration;
import java.text.MessageFormat;

public abstract class HTMLGenerator {

    private static final String HEADER = "<HTML>\n" + "<HEAD>\n" +
	"<TITLE>PD Tournament Result</TITLE>\n" + "</HEAD>\n" + 
	"<BODY TEXT=\"#000000\" BGCOLOR=\"#FFFFFF\" LINK=\"#0F0CD9\" VLINK=\"#E90716\">\n";
    private static final String FOOTER = "\n<HR>\n<BR>Generated by IPDLX libraries<BR>Author: <A HREF=\"mailto:jch@cs.nott.ac.uk\">Jan Humble</A><BR>Contact: <A HREF=\"mailto:gxk@cs.nott.ac.uk\">Graham Kendall</A><BR> </HTML>\n";

    public static String tournamentResultToHTML(TournamentResult result) {
	StringBuffer html = new StringBuffer(HEADER);
	html.append("<H1>Prisoner's Dilemma Tournament</H1>");
	html.append("<H2>Results</H2>");
	html.append("<B>Type:</B>" + Tournament.gameTypeToString(result.getTournamentGameType()));
	html.append("<BR><B>Date:</B>" + result.getTournamentDate());
	html.append("<BR><B>Total run time:</B>" + ((double) result.getTotalTournamentTime() / 1000.0) + " secs");
	html.append("<TABLE BORDER=\"1\">");
	html.append("<TR><TH>Ranking<TH>Player<TH>Strategy<TH>Games Played<TH>Won<TH>Tied<TH>Lost<TH>Total Points");
	int i = 0;
	for (Enumeration e = result.getPlayers().elements(); e.hasMoreElements();) {
	    Player p = (Player) e.nextElement();
	    Object[] args = {new Integer(++i),
			     p.getName(), 
			     p.getStrategy().getFullName(),
			     new Integer(p.gamesPlayed),
			     new Integer(p.gamesWon),
			     new Integer(p.gamesTied),
			     new Integer(p.gamesLost),
			     new Double(p.getResult())};
	    html.append(MessageFormat.format("<TR><TD>{0}<TD>{1}<TD>{2}<TD>{3}<TD>{4}<TD>{5}<TD>{6}<TD>{7}", args));  
	}
	html.append("</TABLE>");
	html.append(FOOTER);
	return html.toString();
    }

}

